### PR TITLE
added missing comma from scopes

### PR DESCRIPTION
**Pull request by alustig3**

### CODE REVIEW

**Comment by Lukasa** [comment]
To clarify, this fixes the missing snippets you mentioned in #24, yes?

**Comment by alustig3** [comment]
Yes it fixes the missing snippets. It also fixes comment toggling, including multiline comments that I was requesting at the start of #24

**Comment by Lukasa** [comment]
Hurrah! Well spotted @alustig3, thanks for your help!

**Comment by Lukasa** [comment]
Published fix in 0.10.0.

**Pull request merged**
