### PR TITLE
pretend to be GitHub Flavoured Markdown

### PR DESCRIPTION
**Pull request by hbrls**
I'm not sure if you will like this approach. I've been using it for a while and feel good.

For future possibility that some rst syntax is not covered by markdown, we can still propose new classes. But that will be much less work to do than start from scratch.

### CODE REVIEW

**Comment by Lukasa** [comment]
Thanks for this @hbrls!

Are you aware of any negative effects from this change?

**Comment by hbrls** [comment]
@Lukasa Not now. Can we have some tests then? I'm not sure about how to test text.

**Comment by Lukasa** [comment]
Neither am I!

**Comment by Lukasa** [comment]
:cake: :sparkles:

**Comment by Lukasa** [comment]
Released in v0.4.0.

**Pull request merged**
